Translated into German | Habe die Einstellungen ins Deutsche übersetzt :)
Fabulously-Optimized/fabulously-optimized pull request #183
Opened 2021-12-05 18:29 UTC by nsde

Hope I can support this project this way :) you're awesome, I love this modpack

2021-12-05 18:32 UTC, nsde commented
Let me know if I should shorten some lines!

2021-12-05 19:21 UTC, Madis0 requested changes
Some changes are needed, you can test the language by yourself too:
https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Language-support#translating-mod-menu-helper

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.bettermounthud": "Zeigt Hungerkeulen und XP an, während man auf einem Pferd sitzt\n§8✎ (keine Optionen)",
The first line is too long, cuts off after "auf"

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.continuity": "Verbundene Texturen, woe bei Optifine\n§9✎§8 Mod ein-/ausstellen, Methode, Ressourcenpakete",
Second line cuts off after "Methode"

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.dcch": "Chatverlauf hinweg über Welten und Servern behalten\n§8✎ (keine Optionen)",
First line cuts off after "Servern"

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.dynamicfps": "FPS im Hintergrund verringern\n§9✎§8 Mod ein-/ausstellen, bei Maushover zurücksetzen, ...",
Second line cuts off after "Maushover"

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.enhancedblockentities": "Optimiert Truhen, Schilder, Betten usw.\n§9✎§8 zu optimierende Blöcke, Methode",
Does the second line have to start with a small letter?

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.ferritecore": "Verringert Arbeitsspeicherauslastung\n§8✎ nur fortgeschrittene Optionen)",
First parenthesis missing on second line

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.itemmodelfix": "Fix transparent lines in held items\n§9✎§8 Method",
Untranslated

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.sodium": "Optimiert das Rendern, mehr FPS\n§9✎§8 In den Videoeinstellungen: Optimierungen",
"Videoeinstellungen" should be "Grafikeinstellungen" as that is how it's translated in German

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.reeses-sodium-options": "Vertikale Videoeinstellungen\n§8✎ (keine Optionen)",
Same as above

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.sodium-extra": "Grafikoptionen von Optifine\n§9✎§8 In den Videoeinstellungen: Animationen, Partikel, ...",
Same as above

2021-12-05 19:21 UTC, Madis0 commented on Mod Menu Helper/assets/modmenu/lang/de_de.json
> +    "modmenu.summaryTranslation.yosbr": "Standardeinstellungen des Modpacks\n§9✎§8 Schau ins FO-Wiki, falls du sie zurücksetzen möchtest."
Second line cuts off at "zürücksetzen"

2021-12-06 17:50 UTC, nsde commented
Alright, should be fine now.

2021-12-06 19:19 UTC, merged

2021-12-06 19:19 UTC, Madis0 commented
Thank you!

2021-12-07 18:05 UTC, nsde commented
You're welcome. Is it done now? :)

2021-12-07 18:07 UTC, Madis0 commented
I merged it, so it will be in the next version I release, whenever that is.