Create hi_IN
Fabulously-Optimized/fabulously-optimized pull request #434
Opened 2022-08-04 12:39 UTC by Probattler

Hindi translation of the description.

2022-08-04 12:45 UTC, osfanbuff63 reviewed
Add a `.md` to the file name, but looks good

2022-08-04 12:46 UTC, Probattler commented
Oh forgot about it.

2022-08-04 15:29 UTC, Madis0 requested changes

2022-08-04 15:29 UTC, Madis0 commented on Description/hi_IN.md
> +# Hindi (India)
You can write that in Hindi as well.

2022-08-04 15:29 UTC, Madis0 commented on Description/hi_IN.md
> + एक Fabric-based modpack Minecraft के लिए जो परफॉर्मांस और ग्राफिक्स को बेहतर करने पर अपना ध्यान केंद्रित करता है।
None of those 4 words have local equivalents?

2022-08-04 15:29 UTC, Madis0 commented on Description/hi_IN.md
> + Fabulously Optimized ज्यादतर Optifine से बेहतर साबित होता है क्योंकि उसमे [आधुनिक पेरफॉर्मांस मॉड्स का इस्तेमाल किया गया है][1] जैसे Sodium और Lithium.
```suggestion
 Fabulously Optimized ज्यादतर OptiFine से बेहतर साबित होता है क्योंकि उसमे [आधुनिक पेरफॉर्मांस मॉड्स का इस्तेमाल किया गया है][1] जैसे Sodium और Lithium. 
```

2022-08-04 15:29 UTC, Madis0 commented on Description/hi_IN.md
> + Fabulously Optimized [Optifine के लगभग सभी विभिन्न विशेषताओं को स्पोर्ट करता है][2], जिसमे shaders, connected textures और zoom आते हैं. [एक मुफ्त cape पाएं!][3]
```suggestion
 Fabulously Optimized [OptiFine के लगभग सभी विभिन्न विशेषताओं को स्पोर्ट करता है][2], जिसमे shaders, connected textures और zoom आते हैं. [एक मुफ्त cape पाएं!][3] 
```

2022-08-04 15:29 UTC, Madis0 commented on Description/hi_IN.md
> + Fabulously Optimized [मे कुछ बदलाव हैं][4] जो vanilla भावों को बिल्कुल नहीं बदलता, जैसे ज्यादा chat history, windowed full screen mode और bugfixes सबसे आम मुद्दों के लिए.
Really? Come on, these words can't be untranslatable...

2022-08-04 15:29 UTC, Madis0 commented on Description/hi_IN.md
> + ### इस modpack को उस करके, [आप हमारे following disclaimers से सहमत होते हैं][15].
come on

2022-09-11 16:04 UTC, Madis0 commented on Description/hi-IN.md
> +[![अभी की समीक्षा](https://img.youtube.com/vi/bb8G9X5Q_4I/maxresdefault.jpg)](https://www.youtube.com/watch?v=bb8G9X5Q_4I)
```suggestion
[![अभी की समीक्षा](https://img.youtube.com/vi/K90gsbmhf3w/maxresdefault.jpg)](https://www.youtube.com/watch?v=K90gsbmhf3w)
```
A review in Hindi

2022-09-11 16:05 UTC, Madis0 commented on Description/hi-IN.md
> +
There is a new entry here in upstream btw

2022-10-30 12:56 UTC, Madis0 commented on Description/hi-IN.md
> +> **उत्तर**: नहीं, ये किसी भी सर्वर पर काम करता है जो vannila clients को support करते हैं. [ज्यादा विस्तृत मे उत्तर और सेर्वर से जुड़े टिप्स यहाँ मौजूद हैं.][13] 
> vannila clients को support 

fix vanilla* typo at least, but I believe at least "support" can be translated too

2022-11-20 15:03 UTC, merged

2022-11-20 15:03 UTC, Madis0 commented
Thanks!