Add Ukrainian localization for Mod Menu Helper
Fabulously-Optimized/fabulously-optimized pull request #552
Opened 2022-12-21 14:58 UTC by Den4enko

2022-12-21 18:24 UTC, Madis0 requested changes
Cool! Needs some small tweaks though, you may also find https://fabulously-optimized.github.io/Mod-Menu-Helper-Size-Checker/ helpful.

2022-12-21 18:24 UTC, Madis0 commented on Mod Menu Helper/assets/fo/lang/uk_ua.json
> +  "modmenu.summaryTranslation.antighost": "Виправлення блоків-привидів\n§9✎§8 Клавіши",
```suggestion
  "modmenu.summaryTranslation.antighost": "Введіть /ghost, щоб виправити блоки-привиди\n§9✎§8 Клавіши",
```
The first line should be identical to the next string and I confirmed that it fits

2022-12-21 18:24 UTC, Madis0 commented on Mod Menu Helper/assets/fo/lang/uk_ua.json
> +  "modmenu.summaryTranslation.bobby": "§c*§r Зберігання завантажених чанків видимимі\n§9✎§8 Блокування сутностей, приглушити чанки, зберігати чанки, ...",
Probably will be cut off after `чанки,`, so you could just remove the rest.

2022-12-21 18:24 UTC, Madis0 commented on Mod Menu Helper/assets/fo/lang/uk_ua.json
> +  "modmenu.summaryTranslation.borderlessmining": "Повноекранний режим з Alt+Tab (опц.)\n§9✎§8 Перемикання моду, Підтримка macOS, індивідуальний розмір, ...",
The string is cut off after `macOS,`, so you could just remove the rest.

2022-12-21 18:24 UTC, Madis0 commented on Mod Menu Helper/assets/fo/lang/uk_ua.json
> +  "modmenu.summaryTranslation.colormatic": "Користувацькі кольори OptiFine\n§9✎§8 Чисті небо/порожнеча, згладжування освітлення",
String is cut off after `згладжування`

2022-12-21 18:24 UTC, Madis0 commented on Mod Menu Helper/assets/fo/lang/uk_ua.json
> +  "modmenu.summaryTranslation.fabrishot": "Створення HD скріншотів за натисканням F9\n§9✎§8 Перепризначення F2, роздільна здатність, клавіши, ...",
String is cut off after `здатність,`, so you can remove the rest

2022-12-21 23:01 UTC, Den4enko commented on Mod Menu Helper/assets/fo/lang/uk_ua.json
> +  "modmenu.summaryTranslation.colormatic": "Користувацькі кольори OptiFine\n§9✎§8 Чисті небо/порожнеча, згладжування освітлення",
Just used synonym verb

2022-12-22 18:50 UTC, merged

2022-12-22 18:50 UTC, Madis0 commented
Thank you!