Gradient (AltTo) and increased the size to look good.
Fabulously-Optimized/fabulously-optimized pull request #786
Opened 2023-12-26 08:19 UTC by PSGitHubUser1

Hi Madis0, remember me?

2023-12-27 07:49 UTC, Madis0 requested changes

2023-12-27 07:49 UTC, Madis0 commented on README.md
> +<a href="https://download.fo/install"><img alt="How to install" height="28" src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/8611110/0aaed593-9791-4d24-8a64-8![compact_46h](ht
That is broken

2023-12-27 07:49 UTC, Madis0 commented on README.md
> +<a href="https://download.fo/rate"><img height="60" src="https://github.com/PSGitHubUser1/fabulously-optimized/assets/90406016/c2b91fcf-0d7c-41ec-8af6-b4a5671c8bed"></a>&nbsp;&nbsp;
Try to view it on mobile, it appears stretched

2023-12-28 09:41 UTC, PSGitHubUser1 commented
Is it better now??

2023-12-28 16:18 UTC, Madis0 requested changes

2023-12-28 16:18 UTC, Madis0 commented on README.md
> +<a href="https://wiki.download.fo/"><img alt="Wiki" height="50" src="https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/compact/documentation/gitbook_vector.svg"></a>&nbsp;&nbsp;&nbsp;
Checked on desktop, the increased badge size seems too big to me, current size was fine.

2023-12-28 16:18 UTC, Madis0 commented on README.md
> +<a href="https://wiki.download.fo/"><img alt="Wiki" height="50" src="https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/compact/documentation/gitbook_vector.svg"></a>&nbsp;&nbsp;&nbsp;
The spaces `&nbsp;` make the badges weirdly aligned on mobile.

2024-01-04 18:57 UTC, merged

2024-01-04 18:57 UTC, Madis0 commented
Merged the gradient change. Thanks!